# generated by datamodel-codegen:
#   filename:  matrix.json

from __future__ import annotations

from typing import Annotated, List, Optional

from pydantic import BaseModel, Field


class Matrix(BaseModel):
    distances: Annotated[
        List[int], Field(description='Travel durations (use to be in meters).')
    ]
    errorCodes: Annotated[
        Optional[List[int]],
        Field(description='Error codes to mark unreachable locations.'),
    ] = None
    profile: Annotated[Optional[str], Field(description='A name of profile.')] = None
    timestamp: Annotated[
        Optional[str],
        Field(description='A date in RFC3999 for which routing info is applicable.'),
    ] = None
    travelTimes: Annotated[
        List[int], Field(description='Travel distances (used to be in seconds).')
    ]
